"""project.expected_segments_per_source (품질 검사)

Revision ID: 2ceb56c5a238
Revises: 5baec808b70f
Create Date: 2026-07-17 10:39:11.599596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ceb56c5a238'
down_revision: Union[str, Sequence[str], None] = '5baec808b70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_segments_per_source', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('expected_segments_per_source')

    # ### end Alembic commands ###
