"""collection target + uploaded_by (docs/15)

Revision ID: b24fcfe0578f
Revises: 2ceb56c5a238
Create Date: 2026-07-17 12:34:04.582259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24fcfe0578f'
down_revision: Union[str, Sequence[str], None] = '2ceb56c5a238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_segment_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.String(length=100), nullable=True))

    with op.batch_alter_table('upload_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_histories', schema=None) as batch_op:
        batch_op.drop_column('uploaded_by')

    with op.batch_alter_table('source_files', schema=None) as batch_op:
        batch_op.drop_column('uploaded_by')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('target_segment_count')

    # ### end Alembic commands ###
